### ISSUE TITLE
Em busca de novos mantenedores

### ISSUE THREAD

**Issue by rochacbruno** [facova/python-pagseguro#58]
Olá,

Eu comecei este projeto quando precisei utilizar PagSeguro em um site de ecommerce,

Comecei a lib, utilizei e ainda tenho alguns sites no ar com a lib em funcionamento.

Porém hoje em dia não utilizo mais o PagSeguro e não tenho tempo (nem interesse) para dedicar a esta biblioteca.

Portanto estou a procura de pessoas que possam manter esta biblioteca, já tentei contato com o @Pagseguro acreditando que eles se interessariam em colaborar ou adotar esta biblioteca, mas ainda assim tenho receio de que caso eles se tornem mantenedores possam abandonar a lib assim como já 
fizeram com outras libs para pagseguro em Python.

Eles ja possuem uma versao nova da API (v3) e muitas features como pagamentos recorrentes ainda não estão implementadas aqui e precisariam ser implementadas por alguem que tenha interesse.

Se alguem tem interesse em se tornar mantenedor deste projeto e obter acesso total + acesso ao PyPI responde esta issue.

**Comment by mazulo** [comment]
Já usei a lib há um tempo atrás e me salvou bastante. Tô bem interessado em poder ajudar a manter :smile:

**Comment by rougeth** [comment]
@rochacbruno conhece o Jazzband? https://jazzband.co/ Pode ser uma boa solução.

**Comment by rochacbruno** [comment]
@rougeth ainda não conhecia parece interessante vou dar uma olhada em como funciona

**Comment by rougeth** [comment]
Não tinha visto que o @mazulo tinha comentado, +1 pra ele!! :)

**Comment by rochacbruno** [comment]
@mazulo a principal queixa da galera é sobre pagamento recorrente e API v3  e documentação 
https://github.com/rochacbruno/python-pagseguro/issues

Tá mesmo afim de ajudar com algumas dessas issues?

Se você estiver mesmo afim posso te adicionar como mantenedor aqui e no PyPI ou até mesmo transferir o repositorio para seu github/username se vc preferir!

Dou preferencia a você antes de procurar o esquema do JazzBand :)

**Comment by augustogoulart** [comment]
@rochacbruno estou com o @mazulo. Também usei a lib em projetos e tenho interesse mantê-lá.

**Comment by mazulo** [comment]
@rochacbruno tô super afim! Acabei de conversar com o @augustogoulart e vamos continuar com o projeto :smiley: quanto ao repositório, o que for mais cômodo pra você funciona pra mim também :)

**Comment by mauler** [comment]
Vou começar a acompanhar, eu tenho a minha própia do pagseguro que utilizo em projetos desde de 2014. Talvez eu abandone a minha por esta ou possa mesclar features.

**Comment by rochacbruno** [comment]
Adicionados e com acesso! https://github.com/rochacbruno/python-pagseguro#mantenedores

**Comment by mazulo** [comment]
Valeu @rochacbruno pela oportunidade e confiança! :rocket:

**Comment by mauler** [comment]
Ótimo :)

**Comment by Hernany** [comment]
Obrigado pessoal! Estou começando a usar essa LIB para um projeto aqui na empresa. Se tocarem o projeto irá ajudar muito.

**Comment by davidkwast** [comment]
Vou voltar a trabalhar em projetos que irão utilizar o PagSeguro. Vou estudar a API atual do PagSeguro junto com este projeto. Se eu puder ajudar, postarei aqui novamente.

**Comment by MarcusMann** [comment]
Boa noite,
Estou pensando em manter. Vou fazer uma leitura do projeto hoje e ver a atual situação.

**Comment by rochacbruno** [comment]
Resolvido! repo em transferencia para a Org @pagseguro
